// <auto-generated />
namespace Examplinvi.DbFx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class updatenov4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatenov4));
        
        string IMigrationMetadata.Id
        {
            get { return "201911042226306_updatenov4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
